#default utf coding variables if needed
ENV[LC_ALL]=en_US.UTF-8
ENV[LANG]=en_US.UTF-8

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :certs do
    match(app_identifier: ["com.forest.Moskit", "com.forest.Moskit-test"], type: "appstore", readonly: true)
  end

end
